/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface VRFConsumerInterface extends Interface {
  functions: {
    fulfillRandomness: TypedFunctionDescription<{
      encode([_requestId, _randomness]: [Arrayish, BigNumberish]): string;
    }>;

    nonces: TypedFunctionDescription<{ encode([]: [Arrayish]): string }>;

    randomnessOutput: TypedFunctionDescription<{ encode([]: []): string }>;

    requestId: TypedFunctionDescription<{ encode([]: []): string }>;

    requestRandomness: TypedFunctionDescription<{
      encode([_keyHash, _fee, _seed]: [
        Arrayish,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;
  };

  events: {};
}

export class VRFConsumer extends Contract {
  connect(signerOrProvider: Signer | Provider | string): VRFConsumer;
  attach(addressOrName: string): VRFConsumer;
  deployed(): Promise<VRFConsumer>;

  on(event: EventFilter | string, listener: Listener): VRFConsumer;
  once(event: EventFilter | string, listener: Listener): VRFConsumer;
  addListener(eventName: EventFilter | string, listener: Listener): VRFConsumer;
  removeAllListeners(eventName: EventFilter | string): VRFConsumer;
  removeListener(eventName: any, listener: Listener): VRFConsumer;

  interface: VRFConsumerInterface;

  functions: {
    fulfillRandomness(
      _requestId: Arrayish,
      _randomness: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    nonces(arg0: Arrayish): Promise<BigNumber>;

    randomnessOutput(): Promise<BigNumber>;

    requestId(): Promise<string>;

    requestRandomness(
      _keyHash: Arrayish,
      _fee: BigNumberish,
      _seed: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  fulfillRandomness(
    _requestId: Arrayish,
    _randomness: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  nonces(arg0: Arrayish): Promise<BigNumber>;

  randomnessOutput(): Promise<BigNumber>;

  requestId(): Promise<string>;

  requestRandomness(
    _keyHash: Arrayish,
    _fee: BigNumberish,
    _seed: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    fulfillRandomness(
      _requestId: Arrayish,
      _randomness: BigNumberish
    ): Promise<BigNumber>;

    nonces(arg0: Arrayish): Promise<BigNumber>;

    randomnessOutput(): Promise<BigNumber>;

    requestId(): Promise<BigNumber>;

    requestRandomness(
      _keyHash: Arrayish,
      _fee: BigNumberish,
      _seed: BigNumberish
    ): Promise<BigNumber>;
  };
}
